//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetisyenUygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiyetListesiTbl
    {
        public DiyetListesiTbl()
        {
            this.HastaTbl = new HashSet<HastaTbl>();
        }
    
        public int DiyetId { get; set; }
        public string DiyetAdi { get; set; }
        public string Pazartesi_Sabah { get; set; }
        public string Pazartesi_Oglen { get; set; }
        public string Pazartesi_Aksam { get; set; }
        public string Salı_Sabah { get; set; }
        public string Salı_Oglen { get; set; }
        public string Salı_Aksam { get; set; }
        public string Carsamba_Sabah { get; set; }
        public string Carsamba_Oglen { get; set; }
        public string Carsamba_Aksam { get; set; }
        public string Persembe_Sabah { get; set; }
        public string Persembe_Oglen { get; set; }
        public string Persembe_Aksam { get; set; }
        public string Cuma_Sabah { get; set; }
        public string Cuma_Oglen { get; set; }
        public string Cuma_Aksam { get; set; }
        public string Cumartesi_Sabah { get; set; }
        public string Cumartesi_Oglen { get; set; }
        public string Cumartesi_Aksam { get; set; }
        public string Pazar_Sabah { get; set; }
        public string Pazar_Oglen { get; set; }
        public string Pazar_Aksam { get; set; }
    
        public virtual ICollection<HastaTbl> HastaTbl { get; set; }
    }
}
