//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetisyenUygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaTbl
    {
        public int HastaId { get; set; }
        public string HastaAd { get; set; }
        public string HastaSoyad { get; set; }
        public string HastaTc { get; set; }
        public string Hastalik { get; set; }
        public int HastaninDiyetisyeni { get; set; }
        public int DiyetYontemId { get; set; }
    
        public virtual DiyetisyenTbl DiyetisyenTbl { get; set; }
        public virtual DiyetListesiTbl DiyetListesiTbl { get; set; }
    }
}
