//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetisyenUygulama
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiyetisyenVeriTabaniEntities : DbContext
    {
        public DiyetisyenVeriTabaniEntities()
            : base("name=DiyetisyenVeriTabaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminTbl> AdminTbl { get; set; }
        public DbSet<DiyetisyenTbl> DiyetisyenTbl { get; set; }
        public DbSet<DiyetListesiTbl> DiyetListesiTbl { get; set; }
        public DbSet<HastaTbl> HastaTbl { get; set; }
    }
}
